### ISSUE TITLE
Rename of directory doesnt work

### ISSUE THREAD

**Issue by JozefDropco** [swaechter/smbjwrapper#11] opened 2018-12-20 08:54 UTC
Hi,
I found a bug in rename directory. When I was working on our application I found out the rename doesnt work. First I found out that PATH_SEPARATOR is slash instead of backslash. I put the path as backslash and getParentPath returned always / (isRoot returned true). and the renameTo function requires backslashes otherwise the rename failed as ACCESS_DENIED. Try to simulate it with more nested folders. Maybe its due our infrastructure I am not sure. We are running on DFS

Kind regards,
Jozef

**Comment by swaechter** [comment] 2018-12-20 20:12
Hi Jozef

The library uses slashes and not backslashes, so a slash as path separator should be fine.

The reason why I started with this library was the over-and-over reapting of the server and share name in paths like the file URI (smb://server/share/dir1/dir2/file.txt) and UNC path (\\\\server\share\dir1\dir2\file.txt) - this just annoyed me (You always have to append/build the path over and over in your code). So I started with a object/hierarchy-node based approach that stores the server/share in the connection and doesn't force me to use backslashes.

Can you already provide ma a minimal reproducible example, so I can debug and fix it?

Best,
Simon

**Comment by swaechter** [comment] 2019-10-08 05:21
I am closing this issue. Feel free to provide a KISS exampe so I can reproduce the problem :)

**Closed by swaechter** 2019-10-08 05:21 UTC
